kind: pipeline
name: default

steps:
    - name: build
      image: maven:3.5.0-alpine
      commands:
      - mvn -B clean package
      - mvn install
    
    - name: docker
      image: plugins/docker
      settings:
        repo: prakharjain/springboot
        tage: latest
        username:
           from_secret: docker_username
        password:
           from_secret: docker_password