kind: pipeline
name: default

steps:
    - name: build
      image: maven
      commands:
      - chmod +x mvn
      - mvn clean install
    
    - name: docker
      image: plugins/docker
      settings:
        repo: prakharjain/springboot
        tage: latest
        username:
           from_secret: docker_username
        password:
           from_secret: docker_password